const GET_USERS_LIST = 'GET_USERS_LIST';
const GET_USER_INFO = 'GET_USER_INFO';
const GET_MY_PROFILE = 'GET_MY_PROFILE';
const ADD_USER = 'ADD_USER';
const UPDATE_USER = 'UPDATE_USER';
const UPDATE_USER_N_REDIRECT = 'UPDATE_USER_N_REDIRECT';
const REMOVE_USER = 'REMOVE_USER';

const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
const GET_SESSION = 'GET_SESSION';
const SIGN_OUT = 'SIGN_OUT';

const GET_TEACHERS_LIST = 'GET_TEACHERS_LIST';
const GET_TEACHER_INFO = 'GET_TEACHER_INFO';
const GET_TEACHER_AVAILABILITY = 'GET_TEACHER_AVAILABILITY';
const CLEAR_TEACHER_AVAILABILITY = 'CLEAR_TEACHER_AVAILABILITY';
const ADD_TEACHER = 'ADD_TEACHER';
const UPDATE_TEACHER = 'UPDATE_TEACHER';
const UPDATE_TEACHER_N_REDIRECT = 'UPDATE_TEACHER_N_REDIRECT';
const REMOVE_TEACHER = 'REMOVE_TEACHER';

const GET_USER_APPOINTMENTS_LIST = 'GET_USER_APPOINTMENTS_LIST';
const GET_TEACHER_APPOINTMENTS_LIST = 'GET_TEACHER_APPOINTMENTS_LIST';
const ADD_APPOINTMENT = 'ADD_APPOINTMENT';
const REMOVE_APPOINTMENT = 'REMOVE_APPOINTMENT';

export {
  GET_USERS_LIST, GET_USER_INFO, GET_MY_PROFILE, ADD_USER, UPDATE_USER, REMOVE_USER,
  UPDATE_USER_N_REDIRECT,

  SIGN_IN_REQUEST, GET_SESSION, SIGN_OUT,

  GET_TEACHERS_LIST, GET_TEACHER_INFO, GET_TEACHER_AVAILABILITY, CLEAR_TEACHER_AVAILABILITY,
  ADD_TEACHER, UPDATE_TEACHER, REMOVE_TEACHER, UPDATE_TEACHER_N_REDIRECT,

  GET_USER_APPOINTMENTS_LIST, GET_TEACHER_APPOINTMENTS_LIST, ADD_APPOINTMENT,
  REMOVE_APPOINTMENT,
};
