const USERS_LIST = 'USERS_LIST';
const SHOW_USER = 'SHOW_USER';
const ADD_USER = 'ADD_USER';
const UPDATE_USER = 'UPDATE_USER';
const REMOVE_USER = 'REMOVE_USER';

const TEACHERS_LIST = 'TEACHERS_LIST';
const SHOW_TEACHER = 'SHOW_TEACHER';
const ADD_TEACHER = 'ADD_TEACHER';
const UPDATE_TEACHER = 'UPDATE_TEACHER';
const REMOVE_TEACHER = 'REMOVE_TEACHER';

const APPOINTMENTS_LIST = 'APPOINTMENTS_LIST';
const SHOW_APPOINTMENT = 'SHOW_APPOINTMENT';
const ADD_APPOINTMENT = 'ADD_APPOINTMENT';
const UPDATE_APPOINTMENT = 'UPDATE_APPOINTMENT';
const REMOVE_APPOINTMENT = 'REMOVE_APPOINTMENT';

export {
  USERS_LIST, SHOW_USER, ADD_USER, UPDATE_USER, REMOVE_USER,
  TEACHERS_LIST, SHOW_TEACHER, ADD_TEACHER, UPDATE_TEACHER, REMOVE_TEACHER,
  APPOINTMENTS_LIST, SHOW_APPOINTMENT, ADD_APPOINTMENT, UPDATE_APPOINTMENT, REMOVE_APPOINTMENT,
};
