const GET_USERS_LIST = 'GET_USERS_LIST';
const GET_USER_INFO = 'GET_USER_INFO';
const ADD_USER = 'ADD_USER';
const UPDATE_USER = 'UPDATE_USER';
const REMOVE_USER = 'REMOVE_USER';

const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
const GET_SESSION = 'GET_SESSION';
const SIGN_OUT = 'SIGN_OUT';

const GET_TEACHERS_LIST = 'GET_TEACHERS_LIST';
const GET_TEACHER_INFO = 'GET_TEACHER_INFO';
const ADD_TEACHER = 'ADD_TEACHER';
const UPDATE_TEACHER = 'UPDATE_TEACHER';
const REMOVE_TEACHER = 'REMOVE_TEACHER';

const GET_APPOINTMENTS_LIST = 'GET_APPOINTMENTS_LIST';
const GET_APPOINTMENT_INFO = 'GET_APPOINTMENT_INFO';
const ADD_APPOINTMENT = 'ADD_APPOINTMENT';
const UPDATE_APPOINTMENT = 'UPDATE_APPOINTMENT';
const REMOVE_APPOINTMENT = 'REMOVE_APPOINTMENT';

const SHOW_ERRORS = 'SHOW_ERRORS';

export {
  GET_USERS_LIST, GET_USER_INFO, ADD_USER, UPDATE_USER, REMOVE_USER,

  SIGN_IN_REQUEST, GET_SESSION, SIGN_OUT,

  GET_TEACHERS_LIST, GET_TEACHER_INFO, ADD_TEACHER, UPDATE_TEACHER, REMOVE_TEACHER,

  GET_APPOINTMENTS_LIST, GET_APPOINTMENT_INFO, ADD_APPOINTMENT, UPDATE_APPOINTMENT,
  REMOVE_APPOINTMENT,

  SHOW_ERRORS,
};
